export default [
  {
    id: 1,
    firstname: 'Kit',
    lastname: 'Harrington',
    image: 'src/assets/pictures/actors/kit-harrington.jpg',
  },
  {
    id: 2,
    firstname: 'Emilia',
    lastname: 'Clarke',
    image: 'src/assets/pictures/actors/emilia-clarke.jpg',
  },
  {
    id: 3,
    firstname: 'Peter',
    lastname: 'Dinklage',
    image: 'src/assets/pictures/actors/peter-dinklage.jpg',
  },
  {
    id: 4,
    firstname: 'Steve',
    lastname: 'Carell',
    image: 'src/assets/pictures/actors/steve-carell.jpg',
  },
  {
    id: 5,
    firstname: 'Rainn',
    lastname: 'Wilson',
    image: 'src/assets/pictures/actors/rainn-wilson.jpg',
  },
  {
    id: 6,
    firstname: 'Jenna',
    lastname: 'Fischer',
    image: 'src/assets/pictures/actors/jenna-fischer.jpg',
  },
  {
    id: 7,
    firstname: 'Alvaro',
    lastname: 'Morte',
    image: 'src/assets/pictures/actors/alvaro-morte.jpg',
  },
  {
    id: 8,
    firstname: 'Ursula',
    lastname: 'Corbero',
    image: 'src/assets/pictures/actors/ursula-corbero.jpg',
  },
  {
    id: 9,
    firstname: 'Pedro',
    lastname: 'Alonso',
    image: 'src/assets/pictures/actors/pedro-alonso.jpg',
  },
  {
    id: 10,
    firstname: 'Jim',
    lastname: 'Parsons',
    image: 'src/assets/pictures/actors/jim-parsons.jpg',
  },
  {
    id: 11,
    firstname: 'Johnny',
    lastname: 'Galecki',
    image: 'src/assets/pictures/actors/johnny-galecki.jpg',
  },
  {
    id: 12,
    firstname: 'Kaley',
    lastname: 'Cuoco',
    image: 'src/assets/pictures/actors/kaley-cuoco.jpg',
  },
  {
    id: 13,
    firstname: 'Jung-jae',
    lastname: 'lee',
    image: 'src/assets/pictures/actors/jung-jae-lee.jpg',
  },
  {
    id: 14,
    firstname: 'Park',
    lastname: 'Hae-Soo',
    image: 'src/assets/pictures/actors/park-hae-soo.jpg',
  },
  {
    id: 15,
    firstname: 'Jung',
    lastname: 'Ho-Yeon',
    image: 'src/assets/pictures/actors/jung-ho-yeon.jpg',
  },
  {
    id: 16,
    firstname: 'Mamoru',
    lastname: 'Miyano',
    image: 'src/assets/pictures/actors/unknown-actor.jpg',
  },
  {
    id: 17,
    firstname: 'Shido',
    lastname: 'Nakamura',
    image: 'src/assets/pictures/actors/unknown-actor.jpg',
  },
  {
    id: 18,
    firstname: 'Kappei',
    lastname: 'Yamaguchi',
    image: 'src/assets/pictures/actors/unknown-actor.jpg',
  },
];
